ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'DECLINED';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "ReservationStatus" ADD VALUE IF NOT EXISTS 'NO_SHOW';
